local Themes = {}

Themes.Dark = {
	Regular = Color3.fromRGB(40, 43, 44),
	Soft = Color3.fromRGB(43, 46, 47),
	Mute = Color3.fromRGB(52, 55, 56),
	SuperMute = Color3.fromRGB(77, 83, 86),
	
	Text = Color3.fromRGB(217, 217, 217),
	TextHighlighted = Color3.fromRGB(255, 255, 255),
	TextAlt = Color3.fromRGB(217, 213, 164),
	TextAlt2 = Color3.fromRGB(255, 255, 255),
	
	DarkStroke = Color3.fromRGB(),
	LightStroke = Color3.fromRGB(255, 255, 255),
	
	SelectedWord = Color3.fromRGB(163, 156, 255),
	CorrectWord = Color3.fromRGB(81, 216, 113),
	IncorrectWord = Color3.fromRGB(220, 80, 80),
	
	IncorrectHighlight = Color3.fromRGB(76, 40, 43)
}

Themes.Light = {
	Regular = Color3.fromRGB(226, 226, 226),
	Soft = Color3.fromRGB(226, 226, 226),
	Mute = Color3.fromRGB(241, 241, 241),
	SuperMute = Color3.fromRGB(252, 252, 252),

	Text = Color3.fromRGB(95, 95, 95),
	TextHighlighted = Color3.fromRGB(76, 76, 76),
	TextAlt = Color3.fromRGB(248, 255, 167),
	TextAlt2 = Color3.fromRGB(255, 255, 255),

	DarkStroke = Color3.fromRGB(60, 60, 60),
	LightStroke = Color3.fromRGB(110, 110, 110),

	SelectedWord = Color3.fromRGB(143, 110, 180),
	CorrectWord = Color3.fromRGB(61, 163, 85),
	IncorrectWord = Color3.fromRGB(172, 63, 63),
	
	IncorrectHighlight = Color3.fromRGB(212, 129, 133)
}

Themes.Cobalt = {
	Regular = Color3.fromRGB(37, 39, 44),
	Soft = Color3.fromRGB(39, 41, 47),
	Mute = Color3.fromRGB(48, 54, 63),
	SuperMute = Color3.fromRGB(71, 81, 95),

	Text = Color3.fromRGB(228, 239, 255),
	TextHighlighted = Color3.fromRGB(255, 255, 255),
	TextAlt = Color3.fromRGB(176, 217, 205),
	TextAlt2 = Color3.fromRGB(230, 255, 244),

	DarkStroke = Color3.fromRGB(145, 183, 191),
	LightStroke = Color3.fromRGB(215, 248, 255),

	SelectedWord = Color3.fromRGB(135, 209, 255),
	CorrectWord = Color3.fromRGB(84, 238, 146),
	IncorrectWord = Color3.fromRGB(255, 105, 85),

	IncorrectHighlight = Color3.fromRGB(103, 60, 79)
}

Themes.Violet = {
	Regular = Color3.fromRGB(24, 18, 32),
	Soft = Color3.fromRGB(69, 55, 80),
	Mute = Color3.fromRGB(115, 100, 138),
	SuperMute = Color3.fromRGB(152, 130, 172),

	Text = Color3.fromRGB(229, 228, 255),
	TextHighlighted = Color3.fromRGB(255, 255, 255),
	TextAlt = Color3.fromRGB(255, 84, 255),
	TextAlt2 = Color3.fromRGB(255, 176, 255),

	DarkStroke = Color3.fromRGB(13, 1, 13),
	LightStroke = Color3.fromRGB(249, 212, 255),

	SelectedWord = Color3.fromRGB(216, 110, 235),
	CorrectWord = Color3.fromRGB(61, 163, 85),
	IncorrectWord = Color3.fromRGB(172, 63, 63),

	IncorrectHighlight = Color3.fromRGB(61, 2, 61)
}

return Themes
